model:
  model_name_or_path: 'klue/bert-base'
  dense_model_name_or_path: 'klue/roberta-large'
  config_name: null
  tokenizer_name: null


data:
  data_path: '/data/ephemeral/data'
  overwrite_cache: false
  preprocessing_num_workers: null
  eval_retrieval: true
  top_k_retrieval: 10
  use_faiss: false
  num_neg: 2

train:
  output_dir: './models/train_dataset'
  do_train: true
  do_eval: true
  overwrite_output_dir: true
  report_to: 'wandb'
  per_device_train_batch_size: 3
  per_device_eval_batch_size: 2
  logging_strategy: 'steps'
  logging_steps: 50
  evaluation_strategy: 'epoch'
  save_strategy: 'epoch'
  save_total_limit: 2
  num_train_epochs: 1
  warmup_steps: 300
  seed: 42
  dataloader_num_workers: 4
  logging_first_step: true
  